---
- name: Ensure Python environment is set up on Ubuntu hosts
  hosts: all
  become: yes
  gather_facts: no
  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Install Python 3
      ansible.builtin.apt:
        name: python3
        state: present

    - name: Install python3-six module
      ansible.builtin.apt:
        name: python3-six
        state: present

    - name: Set python interpreter for future tasks
      ansible.builtin.set_fact:
        ansible_python_interpreter: "/usr/bin/python3"
