---
- name: Test server connectivity
  hosts: all
  gather_facts: false
  tasks:
    - name: Test connectivity using command
      ansible.builtin.command: echo "Connection test successful"
      register: connection_result
      changed_when: false
      
    - name: Display connection result
      ansible.builtin.debug:
        msg: "{{ inventory_hostname }} is reachable - {{ connection_result.stdout }}"
